### ISSUE TITLE
The "pronunciation" in wordids.tsv is confusing

### ISSUE THREAD

**Issue by ZhenheZhang** [google/WikipediaHomographData#1]
Hi,
I'm intended to apply this dataset to the validation of my text-normalization system, which is using CMU pronunciation dict. so I need the convention between the CMU dict and IPA. But your "pronunciation" in wordids.tsv is hard to correspond to any conversion template availble online ( take this repo as an example: https://github.com/matthewmorrone/cmudict-ipa). Also, your "pronuaciation" is not exactly the same as the ones on google translate. For example, affect is 'æˌfɛkt / ə'fɛkt, while google translate is əˈfekt / ˈafekt, and on the template I've found is ʌfɛˈkt / ʌfɛˈkt.
Can you offer me some help on how to achieve the conversion between your "pronunciation" and CMU dict? 

Thanks.

**Comment by kylebgorman** [comment]
Hi there,

The transcriptions here are phomemic Mainstream American English, checked
by hand. In my opinion they are totally orthodox. I don't know where the
Google Translate pronunciations are drawn from but the example you cite is
not what I judge to be the most common pronunciation of that word in MAE.
(Perhaps it's descriptve of another dialect of English.)

I don't immediately know the best way to map these onto CMU dictionary
phonemic transcriptions. Three possibilities come to mind:

* Just do it manually. It shouldn't take more than an hour or two since
there are only 300 or so words in this database. I would welcome a PR that
added CMU equivalents to `wordids.tsv` so long as it it was highly accurate.
* Modify that table of CMU/IPA equivalents you found until it suffices.
* Build a statistical model using a g2p-style system.

**Comment by ZhenheZhang** [comment]
Dear Dr, Gorman,

Thanks for your suggestion. I've done the IPA to CMU for the 326 word ids in wordids.tsv manually. It's not a heavy work like you suggested. I'll save the PR as uploading from my side is a bit complicating.
Thanks for your help!

Sincerely,
Zhenhe

**Comment by kylebgorman** [comment]
Glad to hear it worked out! Let me know if you later get a chance to
circulate your translations.
